project 'SwiftHUD.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftHUD' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 3.2.0'

end
